import json
import requests
import os
import base64 
from azure.identity import DefaultAzureCredential
from azure.mgmt.datafactory import DataFactoryManagementClient

subscription_id = "4fc3407d-e164-4150-b5bd-00694b941cb5"
resource_group = "vishantRG"
factory_name = "TestAEVishant"

credential = DefaultAzureCredential()
client = DataFactoryManagementClient(credential, subscription_id)

pipeline = client.pipelines.get(
    resource_group,
    factory_name,
    "pl_test_drift"
)

azure_pipeline = pipeline.as_dict()

github_owner = "vishantgupta"
github_repo = "adf-agent"
github_file_path = "github_pipeline.json"
github_branch = "main"

url = f"https://api.github.com/repos/{github_owner}/{github_repo}/contents/{github_file_path}?ref={github_branch}"

headers = {
    "Authorization": f"token {os.getenv('GITHUB_TOKEN')}",
    "Accept": "application/vnd.github.v3+json"
}

response = requests.get(url, headers=headers)

file_content = response.json()["content"]
decoded_content = base64.b64decode(file_content).decode("utf-8")

github_pipeline = json.loads(decoded_content)

azure_names = [a["name"] for a in azure_pipeline.get("activities", [])]
github_names = [a["name"] for a in github_pipeline.get("activities", [])]

only_in_azure = set(azure_names) - set(github_names)
only_in_github = set(github_names) - set(azure_names)

print("Azure activities:", azure_names)
print("GitHub activities:", github_names)

if not only_in_azure and not only_in_github:
    print("✅ No drift found")
else:
    print("❌ Drift found")

    if only_in_azure:
        print("Only in Azure:", only_in_azure)

    if only_in_github:
        print("Only in GitHub:", only_in_github)


if only_in_azure:
    print("\n🔧 Suggested fix: Update GitHub to match Azure")

    corrected_pipeline = {
        "name": azure_pipeline["name"],
        "activities": azure_pipeline["activities"]
    }

    with open("generated_pipeline.json", "w") as f:
        json.dump(corrected_pipeline, f, indent=2)

    print("✅ Generated file: generated_pipeline.json")


from openai import OpenAI
import os

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

if only_in_azure or only_in_github:

    prompt = f"""
    Azure activities: {azure_names}
    GitHub activities: {github_names}

    Differences:
    Only in Azure: {only_in_azure}
    Only in GitHub: {only_in_github}

    Explain:
    - what changed
    - why it might have happened
    - risks
    - recommended action
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a senior data engineer analyzing pipeline drift."},
            {"role": "user", "content": prompt}
        ]
    )

    print("\n🤖 AI Analysis:\n")
    print(response.choices[0].message.content)


import subprocess

if only_in_azure:
    branch_name = "auto-fix-pipelineV3"

    # create new branch
    subprocess.run(["git", "checkout", "-b", branch_name])

    # replace github file with generated file
    subprocess.run(["cp", "generated_pipeline.json", "github_pipeline.json"])

    # commit changes
    subprocess.run(["git", "add", "."])
    subprocess.run(["git", "commit", "-m", "Auto fix pipeline drift"])

    # push branch
    subprocess.run(["git", "push", "-u", "origin", branch_name])

    print(f"🚀 Branch {branch_name} pushed. Create PR on GitHub.")




url="https://api.github.com/repos/vishantgupta/adf-agent/pulls"

headers = {"Authorization" : f"token {os.getenv('GITHUB_TOKEN')}","Accept": "application/vnd.github.v3+jsn"}

data = {
"title": "Auto-fix ADF Pipeline drift",
"head": "auto-fix-pipelineV3",
"base": "main",
 "body": "This PR Fixes Pipeline drift detected between Azure and Github \n\Generated by agent"}

response = requests.post(url,headers=headers,json=data)
print(response.status_code)
print(response.json()) 

